services:
  data_store:
    image: "postgres:${POSTGRES_VERSION:-latest}"
    environment:
      POSTGRES_DB: "${POSTGRES_DB:-dns_service}"
      POSTGRES_USER: "${POSTGRES_USER:-username}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-password}"
    ports:
      - "${POSTGRES_EXPORT_PORT:-5432}:5432"
    volumes:
      - "postgresData:/var/lib/postgresql/data"
    networks:
      backend:
        aliases:
          - postgres

  app:
    build: .
    ports:
      - "8080:8080"
      - "8079:8079"
    environment:
      POSTGRES_DB: "jdbc:postgresql://postgres:5432/dns_service"
    depends_on:
      - data_store
    networks:
      backend:
        aliases:
          - dns-service

networks:
  backend:

volumes:
  postgresData:
