spring:
  application:
    name: dns-service
  sql:
    init:
      mode: always
  datasource:
    url: ${POSTGRES_DB:jdbc:postgresql://localhost:5432/dns_service}
    username: ${POSTGRES_USER:username}
    password: ${POSTGRES_PASSWORD:password}
    hikari:
      data-source-properties:
        socketTimeout: 600
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
aws:
  r53:
    access-key: ${AWS_ACCESS_KEY_ID:test}
    secret-key: ${AWS_SECRET_KEY_ID:test}
    region: ${AWS_SECRET_KEY_ID:us-east-1}
    role: ${AWS_ACCESS_ROLE:test}
    use-local: ${USE_LOCAL_R53:false}
    local-address: ${R53_LOCAL_ADDRESS:http://localhost:9090/}
    hosted-zone-id: ${R53_HOSTED_ZONE_ID:test}
    endpoint-override: ${AWS_R53_ENDPOINT_OVERRIDE:https://route53.us-east-1.amazonaws.com/}
